global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: saferide-api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3333']

  - job_name: saferide-websocket
    metrics_path: /metrics
    static_configs:
      - targets: ['websocket:3334']
