const fs = require('fs');
const path = require('path');

const {
  AndroidConfig,
  createRunOncePlugin,
  withAndroidManifest,
  withAppBuildGradle,
  withDangerousMod,
  withGradleProperties,
  withMainApplication,
} = require('@expo/config-plugins');

const PLUGIN_NAME = 'withSafeRideLiteRtLm';
const PLUGIN_VERSION = '1.0.0';
const MODULE_IMPORT = 'import com.esheria.saferide.app.localai.SafeRideLiteRtLmPackage';
const MODULE_REGISTRATION = 'add(SafeRideLiteRtLmPackage())';
const GRADLE_MARKER = '// @generated by withSafeRideLiteRtLm';
const RELEASE_SIGNING_MARKER = '// @generated by withSafeRideReleaseSigning';
const PROGUARD_MARKER = '# @generated by withSafeRideLiteRtLm';
const KOTLIN_PACKAGE_PATH = path.join('com', 'esheria', 'saferide', 'app', 'localai');
const KOTLIN_BRIDGE_FILES = [
  'SafeRideLiteRtLmModule.kt',
  'SafeRideLiteRtLmPackage.kt',
];

function insertAfter(source, anchor, value, label) {
  if (source.includes(value)) return source;
  const index = source.indexOf(anchor);
  if (index < 0) throw new Error(`${PLUGIN_NAME}: unable to find ${label}`);
  const position = index + anchor.length;
  return `${source.slice(0, position)}${value}${source.slice(position)}`;
}

function configureMainApplication(source) {
  let next = source;
  if (!next.includes(MODULE_IMPORT)) {
    next = next.replace(/^(package\s+[^\n]+\n)/m, `$1\n${MODULE_IMPORT}\n`);
  }

  if (!next.includes(MODULE_REGISTRATION)) {
    const generatedPackageList = 'PackageList(this).packages.apply {';
    const legacyPackageList = 'val packages = PackageList(this).packages';
    const reactHostPackageList = 'packageList = PackageList(this).packages';
    if (next.includes(generatedPackageList)) {
      next = insertAfter(
        next,
        generatedPackageList,
        `\n        ${MODULE_REGISTRATION}`,
        'generated Expo package list',
      );
    } else if (next.includes(legacyPackageList)) {
      next = insertAfter(
        next,
        legacyPackageList,
        `\n            packages.${MODULE_REGISTRATION}`,
        'legacy ReactNativeHost package list',
      );
    } else if (next.includes(reactHostPackageList)) {
      next = next.replace(
        reactHostPackageList,
        `${reactHostPackageList}.apply {\n        ${MODULE_REGISTRATION}\n      }`,
      );
    } else {
      throw new Error(`${PLUGIN_NAME}: unable to find a supported MainApplication package list`);
    }
  }
  return next;
}

function configureAppBuildGradle(source) {
  let next = source;
  next = insertAfter(
    next,
    'def projectRoot = rootDir.getAbsoluteFile().getParentFile().getAbsolutePath()\n',
    `${RELEASE_SIGNING_MARKER}\n` +
      `def safeRideReleaseKeystorePath = System.getenv("SAFERIDE_ANDROID_KEYSTORE_PATH")?.trim()\n` +
      `def safeRideReleaseStorePassword = System.getenv("SAFERIDE_ANDROID_KEYSTORE_PASSWORD")\n` +
      `def safeRideReleaseKeyAlias = System.getenv("SAFERIDE_ANDROID_KEY_ALIAS")?.trim()\n` +
      `def safeRideReleaseKeyPassword = System.getenv("SAFERIDE_ANDROID_KEY_PASSWORD")\n` +
      `def safeRideReleaseSigningRequired = (\n` +
      `    System.getenv("SAFERIDE_REQUIRE_RELEASE_SIGNING") ?: "false"\n` +
      `).toBoolean()\n` +
      `def safeRideReleaseSigningInputs = [\n` +
      `    safeRideReleaseKeystorePath,\n` +
      `    safeRideReleaseStorePassword,\n` +
      `    safeRideReleaseKeyAlias,\n` +
      `    safeRideReleaseKeyPassword,\n` +
      `]\n` +
      `def safeRideReleaseSigningConfigured = safeRideReleaseSigningInputs.every {\n` +
      `    it != null && !it.toString().trim().isEmpty()\n` +
      `}\n` +
      `def safeRideReleaseSigningPartiallyConfigured = safeRideReleaseSigningInputs.any {\n` +
      `    it != null && !it.toString().trim().isEmpty()\n` +
      `}\n` +
      `if (safeRideReleaseSigningPartiallyConfigured && !safeRideReleaseSigningConfigured) {\n` +
      `    throw new GradleException("SafeRide release signing variables must be supplied together.")\n` +
      `}\n` +
      `if (safeRideReleaseSigningRequired && !safeRideReleaseSigningConfigured) {\n` +
      `    throw new GradleException("SafeRide release signing is required but no complete external keystore configuration was supplied.")\n` +
      `}\n` +
      `def safeRideReleaseKeystoreFile = safeRideReleaseSigningConfigured\n` +
      `    ? file(safeRideReleaseKeystorePath)\n` +
      `    : null\n` +
      `if (safeRideReleaseKeystoreFile != null && !safeRideReleaseKeystoreFile.isFile()) {\n` +
      `    throw new GradleException("SafeRide release signing keystore file is missing.")\n` +
      `}\n`,
    'projectRoot declaration for release signing',
  );
  next = insertAfter(
    next,
    'def projectRoot = rootDir.getAbsoluteFile().getParentFile().getAbsolutePath()\n',
    `${GRADLE_MARKER}\n` +
      `def safeRideLiteRtLmEnabled = (\n` +
      `    findProperty("saferide.litertlm.enabled")\n` +
      `        ?: System.getenv("SAFERIDE_LITERTLM_ENABLED")\n` +
      `        ?: "false"\n` +
      `).toBoolean()\n` +
      `def safeRideLiteRtLmVersion = (\n` +
      `    findProperty("saferide.litertlm.version")\n` +
      `        ?: System.getenv("SAFERIDE_LITERTLM_VERSION")\n` +
      `        ?: "0.16.0"\n` +
      `)\n` +
      `def safeRideLiteRtLmRealRuntimeAllowed = (\n` +
      `    findProperty("saferide.litertlm.realRuntimeAllowed")\n` +
      `        ?: System.getenv("EXPO_PUBLIC_LOCAL_ASSISTANT_ALLOW_REAL_LITERTLM_RUNTIME")\n` +
      `        ?: "false"\n` +
      `).toBoolean()\n`,
    'projectRoot declaration',
  );
  if (!next.includes('signingConfigs {')) {
    throw new Error(`${PLUGIN_NAME}: unable to find Android signingConfigs block`);
  }
  if (!next.includes(`${RELEASE_SIGNING_MARKER}\n        if (safeRideReleaseSigningConfigured)`)) {
    next = next.replace(
      '    signingConfigs {\n',
      `    signingConfigs {\n` +
        `        ${RELEASE_SIGNING_MARKER}\n` +
        `        if (safeRideReleaseSigningConfigured) {\n` +
        `            saferideRelease {\n` +
        `                storeFile safeRideReleaseKeystoreFile\n` +
        `                storePassword safeRideReleaseStorePassword\n` +
        `                keyAlias safeRideReleaseKeyAlias\n` +
        `                keyPassword safeRideReleaseKeyPassword\n` +
        `            }\n` +
        `        }\n`,
    );
  }
  const releaseDebugSigning = 'signingConfig signingConfigs.debug';
  const releaseExternalSigning =
    'signingConfig safeRideReleaseSigningConfigured ? signingConfigs.saferideRelease : signingConfigs.debug';
  if (!next.includes(releaseExternalSigning)) {
    const releaseBlockPattern = /(release\s*\{[\s\S]*?)(signingConfig signingConfigs\.debug)/;
    if (!releaseBlockPattern.test(next)) {
      throw new Error(`${PLUGIN_NAME}: unable to find Android release signing assignment`);
    }
    next = next.replace(releaseBlockPattern, `$1${releaseExternalSigning}`);
  }
  next = insertAfter(
    next,
    'defaultConfig {\n',
    `        ${GRADLE_MARKER}\n` +
      `        buildConfigField "boolean", "SAFERIDE_LITERTLM_REAL_RUNTIME_ALLOWED", safeRideLiteRtLmRealRuntimeAllowed.toString()\n`,
    'defaultConfig block',
  );
  next = insertAfter(
    next,
    'dependencies {\n',
    `    ${GRADLE_MARKER}\n` +
      `    if (safeRideLiteRtLmEnabled) {\n` +
      `        runtimeOnly("com.google.ai.edge.litertlm:litertlm-android:\${safeRideLiteRtLmVersion}")\n` +
      `    }\n`,
    'dependencies block',
  );
  return next;
}

function upsertGradleProperty(items, key, value) {
  let replaced = false;
  const next = [];
  for (const item of items) {
    if (item.type === 'property' && item.key === key) {
      if (!replaced) {
        next.push({ type: 'property', key, value });
        replaced = true;
      }
      continue;
    }
    next.push(item);
  }
  if (!replaced) {
    next.push({ type: 'property', key, value });
  }
  return next;
}

function configureProguard(source) {
  if (source.includes(PROGUARD_MARKER)) return source;
  return `${source.trimEnd()}\n\n${PROGUARD_MARKER}\n` +
    '-keep class com.google.ai.edge.litertlm.** { *; }\n' +
    '-dontwarn com.google.ai.edge.litertlm.**\n';
}

function copyKotlinBridge(platformProjectRoot) {
  const sourceRoot = path.join(
    __dirname,
    'saferide-litertlm',
    'android',
    'src',
    'main',
    'java',
    KOTLIN_PACKAGE_PATH,
  );
  const destinationRoot = path.join(
    platformProjectRoot,
    'app',
    'src',
    'main',
    'java',
    KOTLIN_PACKAGE_PATH,
  );
  fs.mkdirSync(destinationRoot, { recursive: true });

  for (const fileName of KOTLIN_BRIDGE_FILES) {
    const sourcePath = path.join(sourceRoot, fileName);
    if (!fs.existsSync(sourcePath)) {
      throw new Error(`${PLUGIN_NAME}: missing Kotlin bridge template ${sourcePath}`);
    }
    fs.copyFileSync(sourcePath, path.join(destinationRoot, fileName));
  }
}

function withSafeRideLiteRtLm(config) {
  const realRuntimeAllowed = config.extra?.localAssistant?.allowRealLiteRtLmRuntime === true;
  config = withMainApplication(config, mod => {
    if (mod.modResults.language !== 'kt') {
      throw new Error(`${PLUGIN_NAME}: SafeRide requires a Kotlin MainApplication`);
    }
    mod.modResults.contents = configureMainApplication(mod.modResults.contents);
    return mod;
  });

  config = withAppBuildGradle(config, mod => {
    if (mod.modResults.language !== 'groovy') {
      throw new Error(`${PLUGIN_NAME}: SafeRide requires a Groovy app/build.gradle`);
    }
    mod.modResults.contents = configureAppBuildGradle(mod.modResults.contents);
    return mod;
  });

  config = withGradleProperties(config, mod => {
    let properties = upsertGradleProperty(
      mod.modResults,
      'saferide.litertlm.version',
      '0.16.0',
    );
    properties = upsertGradleProperty(
      properties,
      'saferide.litertlm.enabled',
      String(realRuntimeAllowed),
    );
    properties = upsertGradleProperty(
      properties,
      'saferide.litertlm.realRuntimeAllowed',
      String(realRuntimeAllowed),
    );
    properties = upsertGradleProperty(
      properties,
      'android.packagingOptions.doNotStrip',
      '**/liblitertlm*.so,**/libLiteRt*.so',
    );
    mod.modResults = properties;
    return mod;
  });

  config = withAndroidManifest(config, mod => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(mod.modResults);
    const libraries = application['uses-native-library'] ?? [];
    for (const name of ['libvndksupport.so', 'libOpenCL.so']) {
      if (!libraries.some(entry => entry.$?.['android:name'] === name)) {
        libraries.push({
          $: {
            'android:name': name,
            'android:required': 'false',
          },
        });
      }
    }
    application['uses-native-library'] = libraries;
    return mod;
  });

  config = withDangerousMod(config, ['android', async mod => {
    copyKotlinBridge(mod.modRequest.platformProjectRoot);
    const proguardPath = path.join(mod.modRequest.platformProjectRoot, 'app/proguard-rules.pro');
    const source = fs.existsSync(proguardPath) ? fs.readFileSync(proguardPath, 'utf8') : '';
    fs.writeFileSync(proguardPath, configureProguard(source));
    return mod;
  }]);

  return config;
}

module.exports = createRunOncePlugin(withSafeRideLiteRtLm, PLUGIN_NAME, PLUGIN_VERSION);
module.exports._internal = {
  copyKotlinBridge,
  configureAppBuildGradle,
  configureMainApplication,
  configureProguard,
  upsertGradleProperty,
};
